---
title: "Truncated distribution"
author: "Jelka Stojanov"
date: "26/10/2021"
output: html_document
---

Load package

```{r}
library(truncnorm)
library(ggplot2)
library(afex)

options(max.print = 10000)
options(scipen = 999)
`%notin%` <- Negate(`%in%`)
```

Simulate values

```{r}
emotionalReactionsPosOutcome_Empathy <- data.frame(matrix(0, ncol = 300, nrow = 32))
emotionalReactionsNegOutcome_Empathy <- data.frame(matrix(0, ncol = 300, nrow = 32))
emotionalReactions_Apathy <- data.frame(matrix(0, ncol = 200, nrow = 32))

for(i in 1:ncol(emotionalReactionsPosOutcome_Empathy)) {       # for-loop over columns
  emotionalReactionsPosOutcome_Empathy[ , i] <- rtruncnorm(32, a=7, b=11, mean = 9, sd = 1.2)
  emotionalReactionsPosOutcome_Empathy[ , i] <- as.integer(round(emotionalReactionsPosOutcome_Empathy[ , i], digits = 0))
}

for(i in 1:ncol(emotionalReactionsNegOutcome_Empathy)) {       # for-loop over columns
  emotionalReactionsNegOutcome_Empathy[ , i] <- rtruncnorm(32, a=1, b=5, mean = 3, sd = 1.2)
  emotionalReactionsNegOutcome_Empathy[ , i] <- as.integer(round(emotionalReactionsNegOutcome_Empathy[ , i], digits = 0))
}

for(i in 1:ncol(emotionalReactions_Apathy)) {       # for-loop over columns
  emotionalReactions_Apathy[ , i] <- rtruncnorm(32, a=4, b=8, mean = 6, sd = 1.2)
  emotionalReactions_Apathy[ , i] <- as.integer(round(emotionalReactions_Apathy[ , i], digits = 0))
}

# Display means for all columns
min(colMeans(emotionalReactionsPosOutcome_Empathy))
max(colMeans(emotionalReactionsPosOutcome_Empathy))
apply(emotionalReactionsPosOutcome_Empathy, 2, mean)
apply(emotionalReactionsPosOutcome_Empathy, 2, sd)

min(colMeans(emotionalReactionsNegOutcome_Empathy))
max(colMeans(emotionalReactionsNegOutcome_Empathy))
apply(emotionalReactionsNegOutcome_Empathy, 2, mean)
apply(emotionalReactionsNegOutcome_Empathy, 2, sd)

min(colMeans(emotionalReactions_Apathy))
max(colMeans(emotionalReactions_Apathy))
apply(emotionalReactions_Apathy, 2, mean)
apply(emotionalReactions_Apathy, 2, sd)

# Save csv files
write.csv(emotionalReactionsPosOutcome_Empathy, 'emotionalReactionsPosOutcome_Empathy_32.csv')
write.csv(emotionalReactionsNegOutcome_Empathy, 'emotionalReactionsNegOutcome_Empathy_32.csv')
write.csv(emotionalReactions_Apathy, 'emotionalReactions_Apathy_32.csv')
```

```{r}
#WITHIN-GROUP REACTIONS: Always the same!
emotionalReactions$posOutcome_withinGroup <- rtruncnorm(1000, a=1, b=9, mean = 7.5, sd = 2)
emotionalReactions$negOutcome_withinGroup <- rtruncnorm(1000, a=1, b=9, mean = 2.5, sd = 2)

#BETWEEN-GROUP REACTIONS: Vary with condition!

#CONGRUENT
#First abbreviation: In - Out; Second abbreviation: Out - In
emotionalReactions$posOutcome_betweenGroup_Emp_Emp <- rtruncnorm(1000, a=1, b=9, mean = 7.5, sd = 2)
emotionalReactions$negOutcome_betweenGroup_Emp_Emp <- rtruncnorm(1000, a=1, b=9, mean = 2.5, sd = 2)

emotionalReactions$posOutcome_betweenGroup_Apa_Apa <- rtruncnorm(1000, a=1, b=9, mean = 5, sd = 2)
emotionalReactions$negOutcome_betweenGroup_Apa_Apa <- rtruncnorm(1000, a=1, b=9, mean = 5, sd = 2)


#INCONGRUENT
emotionalReactions$posOutcome_betweenGroup_Emp_Apa_IN <- rtruncnorm(1000, a=1, b=9, mean = 7.5, sd = 2)
emotionalReactions$negOutcome_betweenGroup_Emp_Apa_IN <- rtruncnorm(1000, a=1, b=9, mean = 2.5, sd = 2)

emotionalReactions$posOutcome_betweenGroup_Emp_Apa_OUT <- rtruncnorm(1000, a=1, b=9, mean = 5, sd = 2)
emotionalReactions$negOutcome_betweenGroup_Emp_Apa_OUT <- rtruncnorm(1000, a=1, b=9, mean = 5, sd = 2)

emotionalReactions$posOutcome_betweenGroup_Apa_Emp_IN <- rtruncnorm(1000, a=1, b=9, mean = 5, sd = 2)
emotionalReactions$negOutcome_betweenGroup_Apa_Emp_IN <- rtruncnorm(1000, a=1, b=9, mean = 5, sd = 2)

emotionalReactions$posOutcome_betweenGroup_Apa_Emp_OUT <- rtruncnorm(1000, a=1, b=9, mean = 7.5, sd = 2)
emotionalReactions$negOutcome_betweenGroup_Apa_Emp_OUT <- rtruncnorm(1000, a=1, b=9, mean = 2.5, sd = 2)

#Rounding to integers

#WITHIN-GROUP:
emotionalReactions$posOutcome_withinGroup_Rounded <- as.integer(round(emotionalReactions$posOutcome_withinGroup, digits = 0))
emotionalReactions$negOutcome_withinGroup_Rounded <- as.integer(round(emotionalReactions$negOutcome_withinGroup, digits = 0))

#BETWEEN-GROUP (CONGRUENT):
emotionalReactions$posOutcome_betweenGroup_Emp_Emp_Rounded <- as.integer(round(emotionalReactions$posOutcome_betweenGroup_Emp_Emp, digits = 0))
emotionalReactions$negOutcome_betweenGroup_Emp_Emp_Rounded <- as.integer(round(emotionalReactions$negOutcome_betweenGroup_Emp_Emp, digits = 0))

emotionalReactions$posOutcome_betweenGroup_Apa_Apa_Rounded <- as.integer(round(emotionalReactions$posOutcome_betweenGroup_Apa_Apa, digits = 0))
emotionalReactions$negOutcome_betweenGroup_Apa_Apa_Rounded <- as.integer(round(emotionalReactions$negOutcome_betweenGroup_Apa_Apa, digits = 0))

#BETWEEN-GROUP (INCONGRUENT):
emotionalReactions$posOutcome_betweenGroup_Emp_Apa_IN_Rounded <- as.integer(round(emotionalReactions$posOutcome_betweenGroup_Emp_Apa_IN, digits = 0))
emotionalReactions$negOutcome_betweenGroup_Emp_Apa_IN_Rounded <- as.integer(round(emotionalReactions$negOutcome_betweenGroup_Emp_Apa_IN, digits = 0))

emotionalReactions$posOutcome_betweenGroup_Emp_Apa_OUT_Rounded <- as.integer(round(emotionalReactions$posOutcome_betweenGroup_Emp_Apa_OUT, digits = 0))
emotionalReactions$negOutcome_betweenGroup_Emp_Apa_OUT_Rounded <- as.integer(round(emotionalReactions$negOutcome_betweenGroup_Emp_Apa_OUT, digits = 0))

emotionalReactions$posOutcome_betweenGroup_Apa_Emp_IN_Rounded <- as.integer(round(emotionalReactions$posOutcome_betweenGroup_Apa_Emp_IN, digits = 0))
emotionalReactions$negOutcome_betweenGroup_Apa_Emp_IN_Rounded <- as.integer(round(emotionalReactions$negOutcome_betweenGroup_Apa_Emp_IN, digits = 0))

emotionalReactions$posOutcome_betweenGroup_Apa_Emp_OUT_Rounded <- as.integer(round(emotionalReactions$posOutcome_betweenGroup_Apa_Emp_OUT, digits = 0))
emotionalReactions$negOutcome_betweenGroup_Apa_Emp_OUT_Rounded <- as.integer(round(emotionalReactions$negOutcome_betweenGroup_Apa_Emp_OUT, digits = 0))

emotionalReactions$Participant <- 1:1000
```

Check whether there is a statistically significant difference between the apathy/empathy distributions

```{r}
emotionalReactions_ANOVA <- select(emotionalReactions, c(Participant, posOutcome_betweenGroup_Emp_Apa_OUT, negOutcome_betweenGroup_Emp_Apa_OUT, posOutcome_betweenGroup_Emp_Apa_IN, negOutcome_betweenGroup_Emp_Apa_IN))

emotionalReactions_ANOVA <- gather(emotionalReactions_ANOVA, 'Condition', 'Value', -Participant)
View(emotionalReactions_ANOVA)

emotionalReactions_ANOVA$Outcome <- if_else(grepl('posOutcome', emotionalReactions_ANOVA$Condition), 'Positive', 'Negative')

emotionalReactions_ANOVA$Emp_Apa <- if_else(emotionalReactions_ANOVA$Condition %in% c('posOutcome_betweenGroup_Emp_Apa_IN', 'negOutcome_betweenGroup_Emp_Apa_IN'), 'Empathy', 'Apathy')

anovaCheck <- aov_ez(
   id = 'Participant',
   dv = 'Value',
   data = emotionalReactions_ANOVA,
   within = c('Emp_Apa', 'Outcome'),
   factorize = TRUE)

summary(anovaCheck)

#Condition met
emmeans::emmeans(anovaCheck, ~ Emp_Apa * Outcome, contr = "pairwise", adjust = 'bonferroni')
```

Export the simulated values to a .csv

```{r}
emotionalReactions_NoParticipant <- select(emotionalReactions, -Participant)
write.csv(emotionalReactions_NoParticipant, 'simulatedEmotionalReactions.csv')
```

Plot the histograms

```{r}
ggplot(emotionalReactions) +
  geom_density(aes(x = posOutcome_withinGroup)) +
  geom_vline(xintercept = mean(posOutcome_withinGroup)) +
  annotate('rect', xmin = mean(posOutcome_withinGroup) - sd(posOutcome_withinGroup), 
  xmax = mean(posOutcome_withinGroup) + sd(posOutcome_withinGroup), ymin = 0, ymax = 0.75, alpha = 0.3)

ggplot(emotionalReactions) +
  geom_density(aes(x = negOutcome_withinGroup)) +
  geom_vline(xintercept = mean(negOutcome_withinGroup)) +
  annotate('rect', xmin = mean(negOutcome_withinGroup) - sd(negOutcome_withinGroup), 
  xmax = mean(negOutcome_withinGroup) + sd(negOutcome_withinGroup), ymin = 0, ymax = 0.75, alpha = 0.3)

ggplot(emotionalReactions) +
  geom_histogram(aes(x = posOutcome_withinGroup_Rounded)) 

ggplot(emotionalReactions) +
  geom_histogram(aes(x = negOutcome_withinGroup_Rounded))
```
